### ISSUE TITLE
test_dotfile_generation failed

### ISSUE THREAD

**Issue by guillaume-gricourt** [SynBioDex/SBOL-utilities#134]
Hi,
The unit test  `test_dotfile_generation` is failling from the version `1.0a16`.
I attached my conda environment and the dot file generated during the test. 
I don't know well how a dot file is composed but, the positions of the figures in the image seem to be different between the file generated and the test file
[env.graph_sbol.txt](https://github.com/SynBioDex/SBOL-utilities/files/8940939/env.graph_sbol.txt)
[test.zip](https://github.com/SynBioDex/SBOL-utilities/files/8940940/test.zip)

**Comment by jakebeal** [comment]
Is this on Windows? We recently found that this was not stable between Linux and Mac either, and have temporarily disabled it for Mac. It may be appropriate to disable it for Windows as well.

**Comment by guillaume-gricourt** [comment]
Unfortunately, it appeared on Linux, Ubuntu 20.04.1

**Comment by jakebeal** [comment]
Hmm... I suspect that either the test is too rigid or the materials being generated aren't constrained enough, so that there's too much flexibility.

**Comment by guillaume-gricourt** [comment]
Yes I agree

**Comment by jakebeal** [comment]
Let us simply mark this test as known-failing for now. We will revisit it later, but this shouldn't be allowed to hold up use of the rest of the system in Bioconda.

**Comment by jakebeal** [comment]
It looks like different rendering on different platforms is a known issue caused by differences in fonts (and possibly other things). https://stackoverflow.com/questions/54743233/graphviz-portability-and-fonts-how-make-schemes-identical-on-different-oss

Digging into the test, it looks like the right thing to do is to make sure that we can produce an identical _input_ file and that we can generate _some_ rendering, but not to check the rendering content.
